In [114]:
import numpy as np
import pandas as pd

In [115]:
G = np.array('''
12.0
11.85
11.75
11.6
11.7
11.6
11.5
11.4
82.7
81.7
81.0
80.0
80.7
80.0
79.3
78.6
'''.split('\n')[1:-1]).astype(float).reshape(2, 8).T

data = '''
11.2 77.2 11.2 77.2 11.2 77.2 11.2 77.2 11.2 77.2 10 69.0 11 75.8 11.2 77.2 11.2 77.2 11.5 79.3 6 41.4 6.5 44.8 7.3 50.3 11.2 77.2
'''.split(' ')

G = np.concatenate([
        G, np.concatenate([
            np.array(data[::2], dtype=float).reshape(-1, 1),
            np.array(data[1::2], dtype=float).reshape(-1, 1)
        ], axis=1)
    ], 
    axis=0
)

G

array([[12.  , 82.7 ],
       [11.85, 81.7 ],
       [11.75, 81.  ],
       [11.6 , 80.  ],
       [11.7 , 80.7 ],
       [11.6 , 80.  ],
       [11.5 , 79.3 ],
       [11.4 , 78.6 ],
       [11.2 , 77.2 ],
       [11.2 , 77.2 ],
       [11.2 , 77.2 ],
       [11.2 , 77.2 ],
       [11.2 , 77.2 ],
       [10.  , 69.  ],
       [11.  , 75.8 ],
       [11.2 , 77.2 ],
       [11.2 , 77.2 ],
       [11.5 , 79.3 ],
       [ 6.  , 41.4 ],
       [ 6.5 , 44.8 ],
       [ 7.3 , 50.3 ],
       [11.2 , 77.2 ]])

In [116]:
E = np.array('''
29.5
29.0
28.5
28.0
28.8
28.7
28.6
28.5
203.4
200
196.5
193
198.6
197.9
197.2
196.5
'''.split('\n')[1: -1]).astype(float).reshape(2, 8).T

E = np.concatenate([
        E, np.array('''
28.5 196.5 29.5 203.4 29.5 203.4 29.5 203.4 29.5 203.4 28 193 29.5 208.4 29 200 29 200 30 206 15 103.4 17 117.2 19 131 31 213.7
'''.split(' ')).astype(float).reshape(14, 2)
    ], 
    axis=0
)

E

array([[ 29.5, 203.4],
       [ 29. , 200. ],
       [ 28.5, 196.5],
       [ 28. , 193. ],
       [ 28.8, 198.6],
       [ 28.7, 197.9],
       [ 28.6, 197.2],
       [ 28.5, 196.5],
       [ 28.5, 196.5],
       [ 29.5, 203.4],
       [ 29.5, 203.4],
       [ 29.5, 203.4],
       [ 29.5, 203.4],
       [ 28. , 193. ],
       [ 29.5, 208.4],
       [ 29. , 200. ],
       [ 29. , 200. ],
       [ 30. , 206. ],
       [ 15. , 103.4],
       [ 17. , 117.2],
       [ 19. , 131. ],
       [ 31. , 213.7]])

In [117]:
diameter_range = np.array(
'''
<0.032
0.033-0.063
0.064-0.125
>0.125
<0.032
0.033-0.063
0.064-0.125
>0.125
'''.split('\n')[1:-1]
)

diameter_range = np.concatenate([
        diameter_range,
        (E.shape[0] - len(diameter_range)) * ['']
]).astype(str)

diameter_range.shape

(22,)

In [118]:
limit_elastic = np.array('''
65-75
45-60
60-70
45-55
'''.split('\n')[1:-1]).reshape(2, 2).repeat(4, axis=0)

data = '''85-90 45-50 85-90 50-60 88-93 65-75 88-93
85-93 65-75
65-75 45-55 75-80 55-60 65-70 42-55 65-75 45-55 72-76 50-55 75-80 45-50 70 50
75 50-55 65-70 40-45'''

data = data.replace('\n', ' ').split(' ')
data.insert(7, '')
data = np.array(data).reshape(-1, 1).reshape(14, 2)

limit_elastic = np.concatenate([
        limit_elastic,
        data
    ],
    axis=0
)

limit_elastic

array([['65-75', '45-60'],
       ['65-75', '45-60'],
       ['65-75', '45-60'],
       ['65-75', '45-60'],
       ['60-70', '45-55'],
       ['60-70', '45-55'],
       ['60-70', '45-55'],
       ['60-70', '45-55'],
       ['85-90', '45-50'],
       ['85-90', '50-60'],
       ['88-93', '65-75'],
       ['88-93', ''],
       ['85-93', '65-75'],
       ['65-75', '45-55'],
       ['75-80', '55-60'],
       ['65-70', '42-55'],
       ['65-75', '45-55'],
       ['72-76', '50-55'],
       ['75-80', '45-50'],
       ['70', '50'],
       ['75', '50-55'],
       ['65-70', '40-45']], dtype='<U5')

In [119]:
np.concatenate([E, G], axis=1)

array([[ 29.5 , 203.4 ,  12.  ,  82.7 ],
       [ 29.  , 200.  ,  11.85,  81.7 ],
       [ 28.5 , 196.5 ,  11.75,  81.  ],
       [ 28.  , 193.  ,  11.6 ,  80.  ],
       [ 28.8 , 198.6 ,  11.7 ,  80.7 ],
       [ 28.7 , 197.9 ,  11.6 ,  80.  ],
       [ 28.6 , 197.2 ,  11.5 ,  79.3 ],
       [ 28.5 , 196.5 ,  11.4 ,  78.6 ],
       [ 28.5 , 196.5 ,  11.2 ,  77.2 ],
       [ 29.5 , 203.4 ,  11.2 ,  77.2 ],
       [ 29.5 , 203.4 ,  11.2 ,  77.2 ],
       [ 29.5 , 203.4 ,  11.2 ,  77.2 ],
       [ 29.5 , 203.4 ,  11.2 ,  77.2 ],
       [ 28.  , 193.  ,  10.  ,  69.  ],
       [ 29.5 , 208.4 ,  11.  ,  75.8 ],
       [ 29.  , 200.  ,  11.2 ,  77.2 ],
       [ 29.  , 200.  ,  11.2 ,  77.2 ],
       [ 30.  , 206.  ,  11.5 ,  79.3 ],
       [ 15.  , 103.4 ,   6.  ,  41.4 ],
       [ 17.  , 117.2 ,   6.5 ,  44.8 ],
       [ 19.  , 131.  ,   7.3 ,  50.3 ],
       [ 31.  , 213.7 ,  11.2 ,  77.2 ]])

In [120]:
df = pd.DataFrame(
    np.concatenate([limit_elastic, E, G], axis=1), 
    columns=['Limite tension', 'limite torsion', 'E M-psi', 'E GPa', 'G M-psi', 'G GPa', ], 
)

df['Diámetro in'] = diameter_range

df.head()

Limite tension limite torsion E M-psi  E GPa G M-psi G GPa  Diámetro in
0          65-75          45-60    29.5  203.4    12.0  82.7       <0.032
1          65-75          45-60    29.0  200.0   11.85  81.7  0.033-0.063
2          65-75          45-60    28.5  196.5   11.75  81.0  0.064-0.125
3          65-75          45-60    28.0  193.0    11.6  80.0       >0.125
4          60-70          45-55    28.8  198.6    11.7  80.7       <0.032

In [121]:
material =  np.array(
    '''
Alambre de piano A228
Resorte estirado duro A227
    '''.split('\n')[1:-1]
).repeat(4)

material = np.concatenate([
        material,
        '''
Templado en aceite A239 
Resorte de válvula A230 
Cromo-vanadio A231
Cromo-vanadio A232 
Cromo-silicio A401
Acero inoxidable A313*
Acero inoxidable 17-7PH 
Acero inoxidable 414 
Acero inoxidable 420 
Acero inoxidable 431
Bronce fosforado B159 
Cobre al berilio B197
Cobre al berilio B197
Aleación inconel X-750
'''.split('\n')[1:-1]
])

material.shape

df['Material'] = material

In [122]:
df.describe()

Limite tension limite torsion E M-psi  E GPa G M-psi G GPa Diámetro in   
count              22             22      22     22      22    22          22  \
unique             10             11      12     13      13    13           5   
top             65-75          45-55    29.5  203.4    11.2  77.2               
freq                6              6       6      5       8     8          14   

                     Material  
count                      22  
unique                     15  
top     Alambre de piano A228  
freq                        4

In [123]:
# put material first
df = df[['Material', 'Limite tension', 'limite torsion', 'Diámetro in', 'E M-psi', 'E GPa', 'G M-psi', 'G GPa', ]]

In [124]:
df

Material Limite tension limite torsion  Diámetro in   
0        Alambre de piano A228          65-75          45-60       <0.032  \
1        Alambre de piano A228          65-75          45-60  0.033-0.063   
2        Alambre de piano A228          65-75          45-60  0.064-0.125   
3        Alambre de piano A228          65-75          45-60       >0.125   
4   Resorte estirado duro A227          60-70          45-55       <0.032   
5   Resorte estirado duro A227          60-70          45-55  0.033-0.063   
6   Resorte estirado duro A227          60-70          45-55  0.064-0.125   
7   Resorte estirado duro A227          60-70          45-55       >0.125   
8     Templado en aceite A239           85-90          45-50                
9     Resorte de válvula A230           85-90          50-60                
10          Cromo-vanadio A231          88-93          65-75                
11         Cromo-vanadio A232           88-93                               
12          Cromo-silicio A401          85-93          65-75                
13      Acero inoxidable A313*          65-75          45-55                
14    Acero inoxidable 17-7PH           75-80          55-60                
15       Acero inoxidable 414           65-70          42-55                
16       Acero inoxidable 420           65-75          45-55                
17        Acero inoxidable 431          72-76          50-55                
18      Bronce fosforado B159           75-80          45-50                
19       Cobre al berilio B197             70             50                
20       Cobre al berilio B197             75          50-55                
21      Aleación inconel X-750          65-70          40-45                

   E M-psi  E GPa G M-psi G GPa  
0     29.5  203.4    12.0  82.7  
1     29.0  200.0   11.85  81.7  
2     28.5  196.5   11.75  81.0  
3     28.0  193.0    11.6  80.0  
4     28.8  198.6    11.7  80.7  
5     28.7  197.9    11.6  80.0  
6     28.6  197.2    11.5  79.3  
7     28.5  196.5    11.4  78.6  
8     28.5  196.5    11.2  77.2  
9     29.5  203.4    11.2  77.2  
10    29.5  203.4    11.2  77.2  
11    29.5  203.4    11.2  77.2  
12    29.5  203.4    11.2  77.2  
13    28.0  193.0    10.0  69.0  
14    29.5  208.4    11.0  75.8  
15    29.0  200.0    11.2  77.2  
16    29.0  200.0    11.2  77.2  
17    30.0  206.0    11.5  79.3  
18    15.0  103.4     6.0  41.4  
19    17.0  117.2     6.5  44.8  
20    19.0  131.0     7.3  50.3  
21    31.0  213.7    11.2  77.2

In [126]:
df.to_csv('./tables/table_10_5.csv', index=False)